#pragma once

#include <stdbool.h>
#include <stdint.h>

#include "esp_err.h"
#include "esp_base_config.h"
#include "esp_base_storage_owner.h"
#include "esp_frp_flash_reader.h"

typedef struct {
    const char *device_id;
    const char *firmware_version;
    const char *chip_model;
    uint32_t flash_size_bytes;
    const char *reset_reason;
    esp_base_storage_owner_t *storage_owner;
    esp_base_storage_owner_t *flash_io_owner;
    const efrp_aead_flash_store_t *frp_flash_store;
} esp_base_protocol_context_t;

/* Load directly into the protocol's long-lived config before the control task starts. */
esp_err_t esp_base_protocol_load_config(uint32_t *revision,
                                        esp_base_storage_owner_t *flash_io_owner);
esp_err_t esp_base_protocol_start(const esp_base_protocol_context_t *context);
/* Before ordinary Container boot, resolve only the exact old-boot pending
 * install/upgrade from the durable ledger and ECS2; leave missing or
 * unprovable facts blocked. Uninstall recovery remains after product boot. */
bool esp_base_protocol_recover_product_package(
    const esp_base_storage_claim_t *claim);
/* Under the boot's long storage claim, create an absent ledger only for a
 * pristine empty binding. Reconcile a PREPARED uninstall from durable ECS2
 * evidence after Container boot, without replaying its physical operation. */
bool esp_base_protocol_prepare_product_ledger(
    const esp_base_storage_claim_t *claim, bool product_empty);
/* True only after the control loop has completed a pass recently. */
bool esp_base_protocol_control_healthy(void);
uint32_t esp_base_protocol_control_progress_count(void);
/* A pending OTA self-test rejects config.set until the slot is confirmed. */
void esp_base_protocol_set_ota_verification_pending(bool pending);
/* The single UUID generated by protocol_start for this boot. */
const char *esp_base_protocol_boot_id(void);
