#pragma once

#include <stdbool.h>
#include <stdint.h>

#include "esp_err.h"
#include "esp_base_config.h"
#include "esp_base_storage_owner.h"
#include "esp_frp_flash_reader.h"

typedef struct {
    const char *device_id;
    const char *firmware_version;
    const char *chip_model;
    uint32_t flash_size_bytes;
    const char *reset_reason;
    esp_base_storage_owner_t *storage_owner;
    esp_base_storage_owner_t *flash_io_owner;
    const efrp_aead_flash_store_t *frp_flash_store;
} esp_base_protocol_context_t;

/* Load directly into the protocol's long-lived config before the control task starts. */
esp_err_t esp_base_protocol_load_config(uint32_t *revision);
esp_err_t esp_base_protocol_start(const esp_base_protocol_context_t *context);
/* Under the boot's long storage claim, create an absent product ledger only
 * after Container proves its exact pristine durable no-package baseline. */
bool esp_base_protocol_prepare_product_ledger(
    const esp_base_storage_claim_t *claim);
/* True only after the control loop has completed a pass recently. */
bool esp_base_protocol_control_healthy(void);
uint32_t esp_base_protocol_control_progress_count(void);
/* A pending OTA self-test rejects config.set until the slot is confirmed. */
void esp_base_protocol_set_ota_verification_pending(bool pending);
/* The single UUID generated by protocol_start for this boot. */
const char *esp_base_protocol_boot_id(void);
